[book]
authors = ["PSI authors"]
language = "en"
multilingual = false
src = "src"
title = "Platform System Interface Specification"

[output.html]
git_repository_url = "https://github.com/platform-system-interface/psi-spec"
